set(XDELTA3_INCLUDE_DIRS "${CMAKE_INSTALL_PREFIX}/include/${PROJECT_NAME}")
set(XDELTA3_LIBRARIES "${CMAKE_INSTALL_PREFIX}/lib/lib${PROJECT_NAME}.a")

# 设置对应的目标
set(XDELTA3_TARGET xdelta3)

set(XDELTA3_FOUND TRUE)
